apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: unir-act3-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  strategy: 
      type: RollingUpdate
      rollingUpdate: 
        maxSurge: 1
        maxUnavailable: 1
#  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo
          imagePullPolicy: Always
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-data
              mountPath: "/data/db"
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-pvc