kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongodb-pv
  namespace: unir-act3-namespace
  labels:
    app: mongodb
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
  awsElasticBlockStore:
    volumeID: aws://us-east-1a/vol-068a743f634c5d1da
    fsType: ext4