apiVersion: v1
kind: Service
metadata:
  name: act3-servicio
  namespace: unir-act3-namespace
spec:
  selector:
    app: act3nodejsmongo
  ports:
    - protocol: TCP
      port: 30000
      targetPort: 3000
  type: LoadBalancer
