version: '3.1'

services:
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: 172.31.92.136
    depends_on:
      - mongodb

  web:
    image: app-web
    container_name: web
    restart: always
    ports:
      - 3000:3000
    volumes:
      - webapp_data:/data/app
    depends_on:
      - mongodb

# volumes:
#   webapp_data:
#   mongo-data:
#     driver: local