version: '3.1'

networks:
  app_net:
    driver: bridge

services:
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - app_net

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb
    networks:
      - app_net

  web:
    image: app-web
    container_name: web
    restart: always
    ports:
      - 3000:3000
    volumes:
      - webapp_data:/data/app
    depends_on:
      - mongodb
    networks:
      - app_net

volumes:
  webapp_data:
  mongo-data:
    driver: local
